# Generated by Django 2.0.2 on 2018-02-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shipping', models.FloatField()),
                ('coffees', models.ManyToManyField(through='coffees.CoffeeOrder', to='coffees.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coffees', models.ManyToManyField(through='coffees.CoffeeUser', to='coffees.Coffee')),
            ],
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.User'),
        ),
        migrations.AddField(
            model_name='coffeeorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.Order'),
        ),
    ]
