# Generated by Django 2.0.3 on 2018-03-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('intensity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeUserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeUserOrderQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.Coffee')),
                ('cuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.CoffeeUserOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('shipping', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='coffeeuserorder',
            name='coffees',
            field=models.ManyToManyField(through='coffees.CoffeeUserOrderQuantity', to='coffees.Coffee'),
        ),
        migrations.AddField(
            model_name='coffeeuserorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.Order'),
        ),
        migrations.AddField(
            model_name='coffeeuserorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coffeeuserorderquantity',
            unique_together={('coffee', 'cuo')},
        ),
        migrations.AlterUniqueTogether(
            name='coffeeuserorder',
            unique_together={('user', 'order')},
        ),
    ]
