# Generated by Django 2.0.2 on 2018-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='intensity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
