# Generated by Django 2.0.2 on 2018-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coffeeuserorderquantity',
            unique_together={('coffee', 'cuo')},
        ),
    ]
