# Generated by Django 2.0.2 on 2018-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0002_auto_20180306_1222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coffeeuserorder',
            unique_together={('user', 'order')},
        ),
    ]
