# Generated by Django 2.0.2 on 2018-02-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0002_coffee_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeuser',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coffees.Order'),
            preserve_default=False,
        ),
    ]
