# Generated by Django 2.0.2 on 2018-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0003_coffeeuser_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeorder',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='coffeeorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coffees',
        ),
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CoffeeOrder',
        ),
    ]
