# Generated by Django 2.0.2 on 2018-02-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0004_auto_20180227_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coffees',
        ),
    ]
